name: Streamlit CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest  # You can change this to 'windows-latest' or 'macos-latest' if needed

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Cache pip dependencies to speed up future builds
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run tests
      - name: Run tests
        run: |
          pytest test.py  # Make sure to use your actual test file name here
          # Example: pytest tests/

      # Step 6: Build Streamlit app (optional, if you want to build it before deploying)
      # - name: Build Streamlit app
      #   run: |
      #     # Example: Build-related commands, like bundling assets, etc.
      #     echo "Building Streamlit app"

      # Step 7: Deploy Streamlit app (optional, depending on your deployment platform)
      # If you're deploying to a platform like Streamlit Cloud, you might not need this step.
      # - name: Deploy Streamlit app (optional)
      #   run: |
      #     # Example: Deploy to your server or platform (e.g., Streamlit Cloud, AWS, Heroku)
      #     echo "Deploying Streamlit app"
